"""Korean presentation text only; ROS values and control identifiers stay intact."""

import re

# Long phrases precede individual state/field names. This also translates
# dynamic feedback and log messages at the display boundary, not their source.
TEXT = {
    'Extreme Robot Manual Hardware Validation': '익스트림 로봇 수동 검증',
    'CONTROL / TEST SCOPE': '제어 / 검증 범위',
    'HOLD TO OPEN': '누르는 동안 열기',
    'HOLD TO CLOSE': '누르는 동안 닫기',
    'EMERGENCY STOP': '비상 정지',
    'TOOL DETACHED': '도구 분리',
    'RESET E-STOP (restart required)': '비상 정지 해제 (재시작 필요)',
    'E-STOP': '비상 정지',
    'Connection / Status': '연결 / 상태',
    'Bridge connection': '제어 노드 연결',
    'U2D2 / serial': '통신 장치 / 시리얼',
    'Tool type': '도구 종류',
    'Tool change request': '도구 변경 요청 상태',
    'Blocked reason': '동작 차단 사유',
    'Profile valid': '설정 유효',
    'Calibration / endpoints valid': '보정 / 끝점 유효',
    'Actuators discovered': '모터 감지',
    'Motion allowed': '동작 허용',
    'FSM state': '상태 머신 상태',
    'Arm contract state': '로봇 팔 제어 상태',
    'Control mode': '제어 모드',
    'Dual synchronization': '두 모터 동기화',
    'Contact sensor': '접촉 센서',
    'Arm Manual Control': '로봇 팔 수동 제어',
    'Current rad': '현재 각도 (라디안)',
    'Target rad': '목표 각도 (라디안)',
    'Jog step (deg)': '이동 간격 (도)',
    'Tool Selection / Ownership': '도구 선택 / 제어 권한',
    'REQUEST TOOL CHANGE': '도구 변경 요청',
    'CANCEL TOOL CHANGE': '도구 변경 요청 취소',
    'REQUEST MODE': '모드 변경 요청',
    'Selected tool': '선택한 도구',
    'Ownership': '제어 권한',
    'End Effector': '말단 도구',
    'ENABLE ID3/ID4': '모터 3 / 4 활성화',
    'DISABLE ID3/ID4': '모터 3 / 4 비활성화',
    'MANUAL DUAL MOTOR RECOVERY (one click only)': '두 모터 수동 복구 (클릭당 한 번 이동)',
    'DUAL ENDPOINT CALIBRATION': '두 모터 끝점 보정',
    'START DUAL CALIBRATION': '두 모터 보정 시작',
    'Calibration step (motor degree)': '보정 이동 간격 (모터 회전각, 도)',
    'CAPTURE OPEN': '현재 위치를 열림 끝점으로 기록',
    'CAPTURE CLOSE': '현재 위치를 닫힘 끝점으로 기록',
    'VALIDATE DUAL CALIBRATION': '두 모터 보정 확인',
    'SAVE DUAL CALIBRATION': '두 모터 보정 저장',
    'Captured endpoint pairs become the only OPEN/CLOSE targets. Capture itself performs reads only.':
        '기록한 두 모터의 끝점을 열기·닫기 목표로 사용합니다. 끝점 기록 시 위치만 읽습니다.',
    'CALIBRATION JOG: spread protection bypassed\nNormal OPEN/CLOSE and legacy gripper JOG remain blocked until READY.':
        '보정 이동 중에는 모터 간 위치 편차 보호가 적용되지 않습니다.\n준비 완료 전에는 일반 열기·닫기와 기존 그리퍼 이동을 사용할 수 없습니다.',
    'GRIPPER JOG': '그리퍼 미세 이동',
    'LEFT / −  (OPEN)': '왼쪽 / − (열기)',
    'LEFT / +  (OPEN)': '왼쪽 / + (열기)',
    'RIGHT / +  (CLOSE)': '오른쪽 / + (닫기)',
    'RIGHT / −  (CLOSE)': '오른쪽 / − (닫기)',
    'Gripper position': '그리퍼 위치',
    'Shortcuts: Left=OPEN jog, Right=CLOSE jog, Space=STOP\n(disabled while editing a field; key auto-repeat ignored)':
        '단축키: 왼쪽 화살표=열기, 오른쪽 화살표=닫기, 스페이스=정지\n(입력란 편집 중에는 사용 안 함, 키 자동 반복은 무시)',
    'Step (tick equivalent)': '이동 간격 (위치 단위)',
    'CLEANER START': '청소기 시작', 'CLEANER STOP': '청소기 정지',
    'READ ONLY DIAGNOSTIC': '읽기 전용 진단', 'START CALIBRATION': '보정 시작',
    'No actuator data': '모터 정보 없음',
    'motor spread': '모터 간 편차', 'actual torque': '실제 토크',
    'hardware error': '하드웨어 오류', 'current/load': '전류/부하',
    'Current/Load': '전류/부하',
    'dual_motor_gripper': '2모터 그리퍼', 'spur_1motor_gripper': '1모터 평기어 그리퍼',
    'gripper_left_pinion_joint': '그리퍼 왼쪽 피니언 관절',
    'gripper_drive_joint': '그리퍼 구동 관절',
    'END_EFFECTOR_ONLY': '말단 도구만', 'FULL_ROBOT': '전체 로봇',
    'OPEN_CAPTURED_WAITING_FOR_CLOSE': '열림 끝점 기록 완료 / 닫힘 끝점 대기',
    'CLOSE_CAPTURED_WAITING_FOR_OPEN': '닫힘 끝점 기록 완료 / 열림 끝점 대기',
    'RECALIBRATION_REQUIRED': '재보정 필요', 'CALIBRATION_REQUIRED': '보정 필요',
    'NOT_APPLICABLE': '해당 없음', 'SYNCHRONIZED': '동기화됨',
    'STOP_REJECTED': '정지 요청 거부', 'STOP_ERROR': '정지 오류',
    'OPENING': '여는 중', 'CLOSING': '닫는 중', 'CLOSED': '닫힘',
    'CAPTURING': '끝점 기록 중', 'VALIDATED': '검증 완료',
    'READY': '준비 완료', 'UNKNOWN': '확인 안 됨', 'UNSET': '미설정',
    'STOPPED': '정지됨', 'STOPPING': '정지 중', 'REQUESTED': '요청됨',
    'SENDING': '명령 전송 중', 'ACTIVE': '동작 중', 'SUCCEEDED': '완료',
    'CANCELED': '취소됨', 'ABORTED': '중단됨', 'REJECTED': '거부됨',
    'FAULT': '고장', 'ERROR': '오류', 'BUSY': '동작 중', 'BLOCKED': '동작 차단',
    'IDLE': '대기', 'STOWED': '접힘', 'INIT': '초기화',
    'FSM': '자동 상태 제어', 'MANUAL': '수동',
    'TRUE': '예', 'FALSE': '아니요', 'True': '예', 'False': '아니요', 'None': '없음',
    'OPEN': '열기', 'CLOSE': '닫기', 'STOP': '정지', 'HOLD': '현재 위치 유지',
    'ON': '켜짐', 'OFF': '꺼짐', 'GO': '이동',
    'Joint': '관절', 'Position': '위치', 'Online': '연결됨', 'Jog': '미세 이동',
    'Captured': '기록한 끝점', 'Ownership denied': '제어 권한 변경 불가',
    'Tool change denied': '도구 변경 불가', 'Restart required': '재시작 필요',
    'Confirm detach': '도구 분리 확인',
    'Mark the current tool as DETACHED and stop it?': '현재 도구를 분리 상태로 표시하고 정지하시겠습니까?',
    'MANUAL is allowed only in IDLE/STOWED; current=': '수동 제어는 대기/접힘 상태에서만 가능합니다. 현재 상태=',
    'ToolManager policy denies changes in ': '도구 관리 정책상 다음 상태에서는 변경할 수 없습니다: ',
    'Runtime hardware reprovisioning is not implemented. Stop the launch, detach safely, then restart with tool_type:=':
        '실행 중 도구 재설정은 지원하지 않습니다. 실행을 종료하고 안전하게 분리한 뒤 다음 도구 설정으로 재시작하세요: ',
    ' is already selected': ' 도구가 이미 선택되어 있습니다',
    'Mode request clicked: requested=': '모드 변경 요청: 요청 모드=', ', approved=': ', 승인된 모드=',
    'Hold-to-run jog blocked by dual safety gate': '두 모터 안전 조건을 만족하지 않아 누름 유지 이동을 차단했습니다',
    'Dual hold-to-run ': '두 모터 누름 유지 이동 ',
    ': endpoint-ratio jog while held': ': 누르는 동안 끝점 비율에 맞춰 이동',
    'Dual hold-to-run released: current-position HOLD requested': '버튼을 떼어 두 모터의 현재 위치 유지를 요청했습니다',
    'Dual jog released: current-position HOLD requested': '이동 입력을 해제하여 두 모터의 현재 위치 유지를 요청했습니다',
    'Operator requested dual torque enable for IDs [3, 4]': '모터 3 / 4의 토크 활성화를 요청했습니다',
    'Operator requested dual torque disable for IDs [3, 4]': '모터 3 / 4의 토크 비활성화를 요청했습니다',
    'Operator requested one-click recovery jog: ID': '한 번 이동하는 수동 복구 요청: 모터 ',
    '° (bridge re-reads actual position)': '° (제어 노드에서 현재 위치를 다시 읽음)',
    'Dual endpoint calibration started (no motor write)': '두 모터 끝점 보정을 시작했습니다 (모터 명령 없음)',
    'Dual calibration one-click jog requested: ID': '두 모터 보정 단일 이동 요청: 모터 ',
    'Dual calibration command requested: ': '두 모터 보정 명령 요청: ',
    'dual endpoint recalibration is required': '두 모터 끝점 재보정이 필요합니다',
    'control scope is not END_EFFECTOR_ONLY': '제어 범위가 말단 도구 전용이 아닙니다',
    'selected tool is not a supported gripper': '선택한 도구는 지원하는 그리퍼가 아닙니다',
    'ownership is not MANUAL': '수동 제어 모드가 아닙니다',
    'bridge/tool safety status is not ready or fresh': '제어 노드/도구 안전 상태가 준비되지 않았거나 오래된 정보입니다',
    'current actuator positions are unavailable': '모터의 현재 위치를 확인할 수 없습니다',
    'motor normalized positions are not synchronized': '모터별 정규화 위치가 동기화되지 않았습니다',
    'Gripper jog blocked: already at profile boundary': '그리퍼 이동 차단: 이미 설정 범위의 끝점입니다',
    'Gripper jog blocked: motor normalized positions disagree ': '그리퍼 이동 차단: 모터별 정규화 위치가 일치하지 않습니다 ',
    'Gripper jog blocked: targets outside ': '그리퍼 이동 차단: 목표가 다음 범위를 벗어납니다 ',
    'Gripper jog blocked: ': '그리퍼 이동 차단: ',
    'Gripper jog request: normalized=': '그리퍼 이동 요청: 정규화 위치=',
    'Diagnostic process finished': '진단 작업이 종료됐습니다',
    'Publishing control mode request: ': '제어 모드 변경 요청 전송: ',
    'calibrated': '보정 완료', 'actuator_ids': '모터 번호',
    'safe_min_tick': '최소 위치 한계', 'safe_max_tick': '최대 위치 한계',
    'open_tick': '열림 끝점', 'close_tick': '닫힘 끝점',
    'profile_velocity': '기본 속도', 'profile_acceleration': '기본 가속도',
    'torque_state': '토크 상태', 'hardware_error': '하드웨어 오류',
    'closed': '닫힘', 'open': '열림', 'cleaner': '청소기',
    'current': '현재 위치', 'target': '목표 위치', 'targets': '목표 위치',
    'error': '오차', 'online': '연결됨', 'positions': '위치', 'position': '위치',
    'torque': '토크', 'spread': '편차', 'limit': '한계', 'step': '이동 간격',
    'start': '시작', 'validate': '검증', 'save': '저장',
    'capture_open': '열림 끝점 기록', 'capture_close': '닫힘 끝점 기록',
}

TEXT.update({
    'FAILED': '실패',
    'Gripper result: status=': '그리퍼 동작 결과: 상태=',
    'error_code': '오류 코드', 'message': '메시지',
    'Gripper STOP accepted=': '그리퍼 정지 승인=',
    '; waiting for result': '; 결과를 기다리는 중',
    'Gripper STOP error: ': '그리퍼 정지 오류: ',
    'control scope is END_EFFECTOR_ONLY': '말단 도구만 제어하도록 설정되어 있습니다',
    'Invalid JSON received on /tool/status': '도구 상태 토픽에서 잘못된 형식의 정보를 받았습니다',
    'Arm command blocked: ': '로봇 팔 명령 차단: ',
    'Gripper command blocked: ': '그리퍼 명령 차단: ',
    'FSM command blocked: ': '상태 제어 명령 차단: ',
    'Calibration command blocked: ': '보정 명령 차단: ',
    'Dual torque request blocked: ': '두 모터 토크 요청 차단: ',
    'Manual recovery jog blocked: ': '수동 복구 이동 차단: ',
    'Dual calibration command blocked: ': '두 모터 보정 명령 차단: ',
    'Manual recovery jog blocked by GUI safety gate': '화면의 안전 조건에 따라 수동 복구 이동이 차단됐습니다',
    'Dual calibration command blocked by GUI safety gate': '화면의 안전 조건에 따라 두 모터 보정 명령이 차단됐습니다',
    'GUI is read-only': '읽기 전용 화면입니다',
    'expected IDs [3, 4]': '모터 3 / 4만 허용됩니다',
    'Gripper action rejected by bridge': '제어 노드가 그리퍼 동작을 거부했습니다',
    'Gripper action accepted': '그리퍼 동작 요청이 승인됐습니다',
    'Gripper action error: ': '그리퍼 동작 오류: ',
    'Gripper result error: ': '그리퍼 결과 오류: ',
    'Gripper STOP: torque disabled; no active goal': '그리퍼 정지: 토크를 껐습니다. 진행 중인 목표가 없습니다',
    'Gripper STOP requested': '그리퍼 정지를 요청했습니다',
    'Gripper cancel response: ': '그리퍼 취소 응답: ',
    'Gripper cancel error: ': '그리퍼 취소 오류: ',
    'Cleaner command blocked: ': '청소기 명령 차단: ',
    'ENABLE ID5': '모터 5 활성화', 'DISABLE ID5': '모터 5 비활성화',
    'SET CURRENT AS OPEN': '현재 위치를 열림 끝점으로 기록',
    'SET CURRENT AS CLOSE': '현재 위치를 닫힘 끝점으로 기록',
    'VALIDATE CALIBRATION': '보정 확인', 'SAVE CALIBRATION': '보정 저장',
    'MOTOR': '모터', 'OUTPUT': '출력 각도',
    'motor normalized spread': '모터별 정규화 위치 편차',
    'Spur Gripper | Current': '평기어 그리퍼 | 현재 위치', 'Target': '목표 위치', 'Error': '오차',
    'Safe range': '안전 범위', 'Mechanical range': '기계적 범위',
    'Safety policy: captured OPEN/CLOSE are the command limits; no hidden endpoint or temporary range is used.':
        '안전 정책: 기록한 열림·닫힘 끝점을 명령 한계로 사용하며, 숨겨진 끝점이나 임시 범위는 사용하지 않습니다.',
    'Output mapping: waiting for ID5 feedback': '출력 각도 변환: 모터 5의 위치 정보 대기 중',
})

_PATTERN = re.compile('|'.join(re.escape(key) for key in sorted(TEXT, key=len, reverse=True)))


def ko(text):
    """Translate only a string being rendered; never modify protocol data."""
    text = str(text)
    text = re.sub(r'arm_joint_(\d+)', r'팔 관절 \1', text)
    text = _PATTERN.sub(lambda match: TEXT[match.group()], text)
    return re.sub(r'\bID(?=\d|\b)', '모터 ', text)
